try {
    throw Error('Well that didn\'t work');
} catch (e) {
    console.log(e);
};